version: "3.8"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "150:80"
      - "151:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    depends_on:
      - backend
      - frontend


  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/pb_data:/pb/pb_data
    expose:
      - 8090


  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - 3000
    depends_on:
      - backend


networks:
  proxy:
    driver: bridge