version: "3.8"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./website:/var/www/website:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - website
      - certbot

  website:
    image: php:8.2-fpm
    container_name: website
    volumes:
      - ./website:/var/www/website


  backend:
    build: 
      context: ./backend
      secrets:
        - backend_build_secrets
    container_name: backend
    secrets:
      - backend_build_secrets
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/pb_data:/pb/pb_data
    expose:
      - "8090"


  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet && nginx -s reload; done;'"



secrets:
  backend_build_secrets:
    file: .env.secret