version: "3.8"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend


  backend:
    build: 
      context: ./backend
      secrets:
        - backend_build_secrets
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/pb_data:/pb/pb_data
    expose:
      - "8090"


  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend


secrets:
  backend_build_secrets:
    file: .env.secret